# Generated by Django 5.2.1 on 2025-05-17 22:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='landmarks/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=512)),
            ],
        ),
    ]
