# Generated by Django 5.2.1 on 2025-05-17 22:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=512),
        ),
    ]
