# Generated by Django 5.2.1 on 2025-05-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_alter_landmark_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='embedding',
            field=models.JSONField(),
        ),
    ]
